### ISSUE TITLE
Can't connect to redis db

### ISSUE THREAD

**Issue by gyosko** [nilsherzig/LLocalSearch#35]
**Describe the bug**
Running `docker-compose up` does not work as expected.

**To Reproduce**
```
git clone https://github.com/nilsherzig/LLocalSearch.git
cd ./LLocalSearch
docker-compose up 
```

**Expected behavior**
Application starts.

**Screenshots**
```
...
chromadb-1  | DEBUG:    [04-04-2024 10:50:37] Starting component SegmentAPI
searxng-1   | 2024-04-04 10:50:37,048 ERROR:searx.redisdb: [searxng (977)] can't connect redis DB ...
searxng-1   | Traceback (most recent call last):
searxng-1   |   File "/usr/lib/python3.11/site-packages/redis/connection.py", line 276, in connect
...
```

**Additional context**

The `docker-compose.yml` has not been modified. The variable for `SEARXNG_DOMAIN` is set as follows:

`- SEARXNG_DOMAIN=http://searxng:8080`

And the container name is:

```
searxng:
    image: docker.io/searxng/searxng:latest
    networks:
      - searxng
      - llm_network
      ...
```
